services:
  request-inbox:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "8080:8080"
    environment:
      - API_MODE=server
      - API_HTTP_PORT=8080
      - DB_ENGINE=badger
      - DB_BADGER_PATH=/app/data
      - GIN_MODE=release
      - CORS_ALLOW_ORIGINS=*
      - ENABLE_PRINT_CONFIG=false
      - ENABLE_CALLBACK_URL_VALIDATION=false
      - ENABLE_LISTING_PUBLIC_INBOX=true
    volumes:
      - inbox-data:/app/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost/api/v1/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  inbox-data:
    driver: local
