version: '3.8'

services:
  api: 
    build:
      context: .
      dockerfile: Dockerfile-api
    command: >
        sh -c "make run-api-hot"
    ports:
      - "8080:8080"
    volumes:
      - ./api:/github.com/jesusnoseq/request-inbox/api
      - ./Makefile:/github.com/jesusnoseq/request-inbox/Makefile
  front: 
    build:
      context: .
      dockerfile: Dockerfile-front
    ports:
      - "3000:3000"
    volumes:
      - ./front:/usr/src/app