// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/jesusnoseq/request-inbox/pkg/login (interfaces: LoginHandler)

// Package login_mock is a generated GoMock package.
package login_mock

import (
	reflect "reflect"

	gin "github.com/gin-gonic/gin"
	gomock "github.com/golang/mock/gomock"
)

// MockLoginHandler is a mock of LoginHandler interface.
type MockLoginHandler struct {
	ctrl     *gomock.Controller
	recorder *MockLoginHandlerMockRecorder
}

// MockLoginHandlerMockRecorder is the mock recorder for MockLoginHandler.
type MockLoginHandlerMockRecorder struct {
	mock *MockLoginHandler
}

// NewMockLoginHandler creates a new mock instance.
func NewMockLoginHandler(ctrl *gomock.Controller) *MockLoginHandler {
	mock := &MockLoginHandler{ctrl: ctrl}
	mock.recorder = &MockLoginHandlerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLoginHandler) EXPECT() *MockLoginHandlerMockRecorder {
	return m.recorder
}

// HandleCallback mocks base method.
func (m *MockLoginHandler) HandleCallback(arg0 *gin.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "HandleCallback", arg0)
}

// HandleCallback indicates an expected call of HandleCallback.
func (mr *MockLoginHandlerMockRecorder) HandleCallback(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleCallback", reflect.TypeOf((*MockLoginHandler)(nil).HandleCallback), arg0)
}

// HandleDeleteLoginUser mocks base method.
func (m *MockLoginHandler) HandleDeleteLoginUser(arg0 *gin.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "HandleDeleteLoginUser", arg0)
}

// HandleDeleteLoginUser indicates an expected call of HandleDeleteLoginUser.
func (mr *MockLoginHandlerMockRecorder) HandleDeleteLoginUser(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleDeleteLoginUser", reflect.TypeOf((*MockLoginHandler)(nil).HandleDeleteLoginUser), arg0)
}

// HandleLogin mocks base method.
func (m *MockLoginHandler) HandleLogin(arg0 *gin.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "HandleLogin", arg0)
}

// HandleLogin indicates an expected call of HandleLogin.
func (mr *MockLoginHandlerMockRecorder) HandleLogin(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleLogin", reflect.TypeOf((*MockLoginHandler)(nil).HandleLogin), arg0)
}

// HandleLoginUser mocks base method.
func (m *MockLoginHandler) HandleLoginUser(arg0 *gin.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "HandleLoginUser", arg0)
}

// HandleLoginUser indicates an expected call of HandleLoginUser.
func (mr *MockLoginHandlerMockRecorder) HandleLoginUser(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleLoginUser", reflect.TypeOf((*MockLoginHandler)(nil).HandleLoginUser), arg0)
}

// HandleLogout mocks base method.
func (m *MockLoginHandler) HandleLogout(arg0 *gin.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "HandleLogout", arg0)
}

// HandleLogout indicates an expected call of HandleLogout.
func (mr *MockLoginHandlerMockRecorder) HandleLogout(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleLogout", reflect.TypeOf((*MockLoginHandler)(nil).HandleLogout), arg0)
}
