// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/jesusnoseq/request-inbox/pkg/handler/apikey (interfaces: APIKeyHandler)

// Package apikey_mock is a generated GoMock package.
package apikey_mock

import (
	reflect "reflect"

	gin "github.com/gin-gonic/gin"
	gomock "github.com/golang/mock/gomock"
)

// MockAPIKeyHandler is a mock of APIKeyHandler interface.
type MockAPIKeyHandler struct {
	ctrl     *gomock.Controller
	recorder *MockAPIKeyHandlerMockRecorder
}

// MockAPIKeyHandlerMockRecorder is the mock recorder for MockAPIKeyHandler.
type MockAPIKeyHandlerMockRecorder struct {
	mock *MockAPIKeyHandler
}

// NewMockAPIKeyHandler creates a new mock instance.
func NewMockAPIKeyHandler(ctrl *gomock.Controller) *MockAPIKeyHandler {
	mock := &MockAPIKeyHandler{ctrl: ctrl}
	mock.recorder = &MockAPIKeyHandlerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAPIKeyHandler) EXPECT() *MockAPIKeyHandlerMockRecorder {
	return m.recorder
}

// CreateAPIKey mocks base method.
func (m *MockAPIKeyHandler) CreateAPIKey(arg0 *gin.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "CreateAPIKey", arg0)
}

// CreateAPIKey indicates an expected call of CreateAPIKey.
func (mr *MockAPIKeyHandlerMockRecorder) CreateAPIKey(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateAPIKey", reflect.TypeOf((*MockAPIKeyHandler)(nil).CreateAPIKey), arg0)
}

// DeleteAPIKey mocks base method.
func (m *MockAPIKeyHandler) DeleteAPIKey(arg0 *gin.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "DeleteAPIKey", arg0)
}

// DeleteAPIKey indicates an expected call of DeleteAPIKey.
func (mr *MockAPIKeyHandlerMockRecorder) DeleteAPIKey(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteAPIKey", reflect.TypeOf((*MockAPIKeyHandler)(nil).DeleteAPIKey), arg0)
}

// GetAPIKey mocks base method.
func (m *MockAPIKeyHandler) GetAPIKey(arg0 *gin.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "GetAPIKey", arg0)
}

// GetAPIKey indicates an expected call of GetAPIKey.
func (mr *MockAPIKeyHandlerMockRecorder) GetAPIKey(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAPIKey", reflect.TypeOf((*MockAPIKeyHandler)(nil).GetAPIKey), arg0)
}

// ListAPIKeysByUser mocks base method.
func (m *MockAPIKeyHandler) ListAPIKeysByUser(arg0 *gin.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "ListAPIKeysByUser", arg0)
}

// ListAPIKeysByUser indicates an expected call of ListAPIKeysByUser.
func (mr *MockAPIKeyHandlerMockRecorder) ListAPIKeysByUser(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAPIKeysByUser", reflect.TypeOf((*MockAPIKeyHandler)(nil).ListAPIKeysByUser), arg0)
}
