// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/jesusnoseq/request-inbox/pkg/handler/apikey (interfaces: IAPIKeyHandler)

// Package apikey_mock is a generated GoMock package.
package apikey_mock

import (
	reflect "reflect"

	gin "github.com/gin-gonic/gin"
	gomock "github.com/golang/mock/gomock"
)

// MockIAPIKeyHandler is a mock of IAPIKeyHandler interface.
type MockIAPIKeyHandler struct {
	ctrl     *gomock.Controller
	recorder *MockIAPIKeyHandlerMockRecorder
}

// MockIAPIKeyHandlerMockRecorder is the mock recorder for MockIAPIKeyHandler.
type MockIAPIKeyHandlerMockRecorder struct {
	mock *MockIAPIKeyHandler
}

// NewMockIAPIKeyHandler creates a new mock instance.
func NewMockIAPIKeyHandler(ctrl *gomock.Controller) *MockIAPIKeyHandler {
	mock := &MockIAPIKeyHandler{ctrl: ctrl}
	mock.recorder = &MockIAPIKeyHandlerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIAPIKeyHandler) EXPECT() *MockIAPIKeyHandlerMockRecorder {
	return m.recorder
}

// CreateAPIKey mocks base method.
func (m *MockIAPIKeyHandler) CreateAPIKey(arg0 *gin.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "CreateAPIKey", arg0)
}

// CreateAPIKey indicates an expected call of CreateAPIKey.
func (mr *MockIAPIKeyHandlerMockRecorder) CreateAPIKey(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateAPIKey", reflect.TypeOf((*MockIAPIKeyHandler)(nil).CreateAPIKey), arg0)
}

// DeleteAPIKey mocks base method.
func (m *MockIAPIKeyHandler) DeleteAPIKey(arg0 *gin.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "DeleteAPIKey", arg0)
}

// DeleteAPIKey indicates an expected call of DeleteAPIKey.
func (mr *MockIAPIKeyHandlerMockRecorder) DeleteAPIKey(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteAPIKey", reflect.TypeOf((*MockIAPIKeyHandler)(nil).DeleteAPIKey), arg0)
}

// GetAPIKey mocks base method.
func (m *MockIAPIKeyHandler) GetAPIKey(arg0 *gin.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "GetAPIKey", arg0)
}

// GetAPIKey indicates an expected call of GetAPIKey.
func (mr *MockIAPIKeyHandlerMockRecorder) GetAPIKey(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAPIKey", reflect.TypeOf((*MockIAPIKeyHandler)(nil).GetAPIKey), arg0)
}

// ListAPIKeysByUser mocks base method.
func (m *MockIAPIKeyHandler) ListAPIKeysByUser(arg0 *gin.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "ListAPIKeysByUser", arg0)
}

// ListAPIKeysByUser indicates an expected call of ListAPIKeysByUser.
func (mr *MockIAPIKeyHandlerMockRecorder) ListAPIKeysByUser(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAPIKeysByUser", reflect.TypeOf((*MockIAPIKeyHandler)(nil).ListAPIKeysByUser), arg0)
}
