// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/jesusnoseq/request-inbox/pkg/handler/apikey (interfaces: APIKeyController)

// Package apikey_mock is a generated GoMock package.
package apikey_mock

import (
	reflect "reflect"

	gin "github.com/gin-gonic/gin"
	gomock "github.com/golang/mock/gomock"
)

// MockAPIKeyController is a mock of APIKeyController interface.
type MockAPIKeyController struct {
	ctrl     *gomock.Controller
	recorder *MockAPIKeyControllerMockRecorder
}

// MockAPIKeyControllerMockRecorder is the mock recorder for MockAPIKeyController.
type MockAPIKeyControllerMockRecorder struct {
	mock *MockAPIKeyController
}

// NewMockAPIKeyController creates a new mock instance.
func NewMockAPIKeyController(ctrl *gomock.Controller) *MockAPIKeyController {
	mock := &MockAPIKeyController{ctrl: ctrl}
	mock.recorder = &MockAPIKeyControllerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAPIKeyController) EXPECT() *MockAPIKeyControllerMockRecorder {
	return m.recorder
}

// CreateAPIKey mocks base method.
func (m *MockAPIKeyController) CreateAPIKey(arg0 *gin.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "CreateAPIKey", arg0)
}

// CreateAPIKey indicates an expected call of CreateAPIKey.
func (mr *MockAPIKeyControllerMockRecorder) CreateAPIKey(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateAPIKey", reflect.TypeOf((*MockAPIKeyController)(nil).CreateAPIKey), arg0)
}

// DeleteAPIKey mocks base method.
func (m *MockAPIKeyController) DeleteAPIKey(arg0 *gin.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "DeleteAPIKey", arg0)
}

// DeleteAPIKey indicates an expected call of DeleteAPIKey.
func (mr *MockAPIKeyControllerMockRecorder) DeleteAPIKey(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteAPIKey", reflect.TypeOf((*MockAPIKeyController)(nil).DeleteAPIKey), arg0)
}

// GetAPIKey mocks base method.
func (m *MockAPIKeyController) GetAPIKey(arg0 *gin.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "GetAPIKey", arg0)
}

// GetAPIKey indicates an expected call of GetAPIKey.
func (mr *MockAPIKeyControllerMockRecorder) GetAPIKey(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAPIKey", reflect.TypeOf((*MockAPIKeyController)(nil).GetAPIKey), arg0)
}

// ListAPIKeysByUser mocks base method.
func (m *MockAPIKeyController) ListAPIKeysByUser(arg0 *gin.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "ListAPIKeysByUser", arg0)
}

// ListAPIKeysByUser indicates an expected call of ListAPIKeysByUser.
func (mr *MockAPIKeyControllerMockRecorder) ListAPIKeysByUser(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAPIKeysByUser", reflect.TypeOf((*MockAPIKeyController)(nil).ListAPIKeysByUser), arg0)
}
