root = "."
tmp_dir = "tmp"

[build]
cmd = "go build -o ./tmp/api.exe ./cmd/main.go"
bin = "tmp/api.exe"
full_bin = "./tmp/api.exe"
delay = 2000
exclude_dir = []
exclude_file = []
exclude_regex = ["_test.go"]
exclude_unchanged = false
follow_symlink = false
include_dir = ["pkg", "cmd"]
include_ext = ["go", "toml"]
kill_delay = "1s"
send_interrupt = false
stop_on_error = false

[log]
time = true

[misc]
clean_on_exit = false

[screen]
clear_on_rebuild = false
