// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/jesusnoseq/request-inbox/pkg/handler (interfaces: InboxHandler)

// Package handler_mock is a generated GoMock package.
package handler_mock

import (
	reflect "reflect"

	gin "github.com/gin-gonic/gin"
	gomock "github.com/golang/mock/gomock"
)

// MockInboxHandler is a mock of InboxHandler interface.
type MockInboxHandler struct {
	ctrl     *gomock.Controller
	recorder *MockInboxHandlerMockRecorder
}

// MockInboxHandlerMockRecorder is the mock recorder for MockInboxHandler.
type MockInboxHandlerMockRecorder struct {
	mock *MockInboxHandler
}

// NewMockInboxHandler creates a new mock instance.
func NewMockInboxHandler(ctrl *gomock.Controller) *MockInboxHandler {
	mock := &MockInboxHandler{ctrl: ctrl}
	mock.recorder = &MockInboxHandlerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockInboxHandler) EXPECT() *MockInboxHandlerMockRecorder {
	return m.recorder
}

// AcceptCookies mocks base method.
func (m *MockInboxHandler) AcceptCookies(arg0 *gin.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "AcceptCookies", arg0)
}

// AcceptCookies indicates an expected call of AcceptCookies.
func (mr *MockInboxHandlerMockRecorder) AcceptCookies(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AcceptCookies", reflect.TypeOf((*MockInboxHandler)(nil).AcceptCookies), arg0)
}

// CreateInbox mocks base method.
func (m *MockInboxHandler) CreateInbox(arg0 *gin.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "CreateInbox", arg0)
}

// CreateInbox indicates an expected call of CreateInbox.
func (mr *MockInboxHandlerMockRecorder) CreateInbox(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateInbox", reflect.TypeOf((*MockInboxHandler)(nil).CreateInbox), arg0)
}

// DeleteInbox mocks base method.
func (m *MockInboxHandler) DeleteInbox(arg0 *gin.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "DeleteInbox", arg0)
}

// DeleteInbox indicates an expected call of DeleteInbox.
func (mr *MockInboxHandlerMockRecorder) DeleteInbox(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteInbox", reflect.TypeOf((*MockInboxHandler)(nil).DeleteInbox), arg0)
}

// DeleteInboxRequests mocks base method.
func (m *MockInboxHandler) DeleteInboxRequests(arg0 *gin.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "DeleteInboxRequests", arg0)
}

// DeleteInboxRequests indicates an expected call of DeleteInboxRequests.
func (mr *MockInboxHandlerMockRecorder) DeleteInboxRequests(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteInboxRequests", reflect.TypeOf((*MockInboxHandler)(nil).DeleteInboxRequests), arg0)
}

// GetInbox mocks base method.
func (m *MockInboxHandler) GetInbox(arg0 *gin.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "GetInbox", arg0)
}

// GetInbox indicates an expected call of GetInbox.
func (mr *MockInboxHandlerMockRecorder) GetInbox(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetInbox", reflect.TypeOf((*MockInboxHandler)(nil).GetInbox), arg0)
}

// Health mocks base method.
func (m *MockInboxHandler) Health(arg0 *gin.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Health", arg0)
}

// Health indicates an expected call of Health.
func (mr *MockInboxHandlerMockRecorder) Health(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Health", reflect.TypeOf((*MockInboxHandler)(nil).Health), arg0)
}

// ListInbox mocks base method.
func (m *MockInboxHandler) ListInbox(arg0 *gin.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "ListInbox", arg0)
}

// ListInbox indicates an expected call of ListInbox.
func (mr *MockInboxHandlerMockRecorder) ListInbox(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListInbox", reflect.TypeOf((*MockInboxHandler)(nil).ListInbox), arg0)
}

// RegisterInboxRequest mocks base method.
func (m *MockInboxHandler) RegisterInboxRequest(arg0 *gin.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "RegisterInboxRequest", arg0)
}

// RegisterInboxRequest indicates an expected call of RegisterInboxRequest.
func (mr *MockInboxHandlerMockRecorder) RegisterInboxRequest(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RegisterInboxRequest", reflect.TypeOf((*MockInboxHandler)(nil).RegisterInboxRequest), arg0)
}

// UpdateInbox mocks base method.
func (m *MockInboxHandler) UpdateInbox(arg0 *gin.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "UpdateInbox", arg0)
}

// UpdateInbox indicates an expected call of UpdateInbox.
func (mr *MockInboxHandlerMockRecorder) UpdateInbox(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateInbox", reflect.TypeOf((*MockInboxHandler)(nil).UpdateInbox), arg0)
}
