// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/jesusnoseq/request-inbox/pkg/handler (interfaces: InboxService,HealthHandler,UtilityHandler)

// Package handler_mock is a generated GoMock package.
package handler_mock

import (
	reflect "reflect"

	gin "github.com/gin-gonic/gin"
	gomock "github.com/golang/mock/gomock"
)

// MockInboxService is a mock of InboxService interface.
type MockInboxService struct {
	ctrl     *gomock.Controller
	recorder *MockInboxServiceMockRecorder
}

// MockInboxServiceMockRecorder is the mock recorder for MockInboxService.
type MockInboxServiceMockRecorder struct {
	mock *MockInboxService
}

// NewMockInboxService creates a new mock instance.
func NewMockInboxService(ctrl *gomock.Controller) *MockInboxService {
	mock := &MockInboxService{ctrl: ctrl}
	mock.recorder = &MockInboxServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockInboxService) EXPECT() *MockInboxServiceMockRecorder {
	return m.recorder
}

// CreateInbox mocks base method.
func (m *MockInboxService) CreateInbox(arg0 *gin.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "CreateInbox", arg0)
}

// CreateInbox indicates an expected call of CreateInbox.
func (mr *MockInboxServiceMockRecorder) CreateInbox(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateInbox", reflect.TypeOf((*MockInboxService)(nil).CreateInbox), arg0)
}

// DeleteInbox mocks base method.
func (m *MockInboxService) DeleteInbox(arg0 *gin.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "DeleteInbox", arg0)
}

// DeleteInbox indicates an expected call of DeleteInbox.
func (mr *MockInboxServiceMockRecorder) DeleteInbox(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteInbox", reflect.TypeOf((*MockInboxService)(nil).DeleteInbox), arg0)
}

// DeleteInboxRequests mocks base method.
func (m *MockInboxService) DeleteInboxRequests(arg0 *gin.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "DeleteInboxRequests", arg0)
}

// DeleteInboxRequests indicates an expected call of DeleteInboxRequests.
func (mr *MockInboxServiceMockRecorder) DeleteInboxRequests(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteInboxRequests", reflect.TypeOf((*MockInboxService)(nil).DeleteInboxRequests), arg0)
}

// GetInbox mocks base method.
func (m *MockInboxService) GetInbox(arg0 *gin.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "GetInbox", arg0)
}

// GetInbox indicates an expected call of GetInbox.
func (mr *MockInboxServiceMockRecorder) GetInbox(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetInbox", reflect.TypeOf((*MockInboxService)(nil).GetInbox), arg0)
}

// ListInbox mocks base method.
func (m *MockInboxService) ListInbox(arg0 *gin.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "ListInbox", arg0)
}

// ListInbox indicates an expected call of ListInbox.
func (mr *MockInboxServiceMockRecorder) ListInbox(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListInbox", reflect.TypeOf((*MockInboxService)(nil).ListInbox), arg0)
}

// RegisterInboxRequest mocks base method.
func (m *MockInboxService) RegisterInboxRequest(arg0 *gin.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "RegisterInboxRequest", arg0)
}

// RegisterInboxRequest indicates an expected call of RegisterInboxRequest.
func (mr *MockInboxServiceMockRecorder) RegisterInboxRequest(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RegisterInboxRequest", reflect.TypeOf((*MockInboxService)(nil).RegisterInboxRequest), arg0)
}

// UpdateInbox mocks base method.
func (m *MockInboxService) UpdateInbox(arg0 *gin.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "UpdateInbox", arg0)
}

// UpdateInbox indicates an expected call of UpdateInbox.
func (mr *MockInboxServiceMockRecorder) UpdateInbox(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateInbox", reflect.TypeOf((*MockInboxService)(nil).UpdateInbox), arg0)
}

// MockHealthHandler is a mock of HealthHandler interface.
type MockHealthHandler struct {
	ctrl     *gomock.Controller
	recorder *MockHealthHandlerMockRecorder
}

// MockHealthHandlerMockRecorder is the mock recorder for MockHealthHandler.
type MockHealthHandlerMockRecorder struct {
	mock *MockHealthHandler
}

// NewMockHealthHandler creates a new mock instance.
func NewMockHealthHandler(ctrl *gomock.Controller) *MockHealthHandler {
	mock := &MockHealthHandler{ctrl: ctrl}
	mock.recorder = &MockHealthHandlerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockHealthHandler) EXPECT() *MockHealthHandlerMockRecorder {
	return m.recorder
}

// Health mocks base method.
func (m *MockHealthHandler) Health(arg0 *gin.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Health", arg0)
}

// Health indicates an expected call of Health.
func (mr *MockHealthHandlerMockRecorder) Health(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Health", reflect.TypeOf((*MockHealthHandler)(nil).Health), arg0)
}

// MockUtilityHandler is a mock of UtilityHandler interface.
type MockUtilityHandler struct {
	ctrl     *gomock.Controller
	recorder *MockUtilityHandlerMockRecorder
}

// MockUtilityHandlerMockRecorder is the mock recorder for MockUtilityHandler.
type MockUtilityHandlerMockRecorder struct {
	mock *MockUtilityHandler
}

// NewMockUtilityHandler creates a new mock instance.
func NewMockUtilityHandler(ctrl *gomock.Controller) *MockUtilityHandler {
	mock := &MockUtilityHandler{ctrl: ctrl}
	mock.recorder = &MockUtilityHandlerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUtilityHandler) EXPECT() *MockUtilityHandlerMockRecorder {
	return m.recorder
}

// AcceptCookies mocks base method.
func (m *MockUtilityHandler) AcceptCookies(arg0 *gin.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "AcceptCookies", arg0)
}

// AcceptCookies indicates an expected call of AcceptCookies.
func (mr *MockUtilityHandlerMockRecorder) AcceptCookies(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AcceptCookies", reflect.TypeOf((*MockUtilityHandler)(nil).AcceptCookies), arg0)
}
