// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/jesusnoseq/request-inbox/pkg/handler (interfaces: InboxController,HealthHandler,UtilityHandler)

// Package handler_mock is a generated GoMock package.
package handler_mock

import (
	reflect "reflect"

	gin "github.com/gin-gonic/gin"
	gomock "github.com/golang/mock/gomock"
)

// MockInboxController is a mock of InboxController interface.
type MockInboxController struct {
	ctrl     *gomock.Controller
	recorder *MockInboxControllerMockRecorder
}

// MockInboxControllerMockRecorder is the mock recorder for MockInboxController.
type MockInboxControllerMockRecorder struct {
	mock *MockInboxController
}

// NewMockInboxController creates a new mock instance.
func NewMockInboxController(ctrl *gomock.Controller) *MockInboxController {
	mock := &MockInboxController{ctrl: ctrl}
	mock.recorder = &MockInboxControllerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockInboxController) EXPECT() *MockInboxControllerMockRecorder {
	return m.recorder
}

// CreateInbox mocks base method.
func (m *MockInboxController) CreateInbox(arg0 *gin.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "CreateInbox", arg0)
}

// CreateInbox indicates an expected call of CreateInbox.
func (mr *MockInboxControllerMockRecorder) CreateInbox(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateInbox", reflect.TypeOf((*MockInboxController)(nil).CreateInbox), arg0)
}

// DeleteInbox mocks base method.
func (m *MockInboxController) DeleteInbox(arg0 *gin.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "DeleteInbox", arg0)
}

// DeleteInbox indicates an expected call of DeleteInbox.
func (mr *MockInboxControllerMockRecorder) DeleteInbox(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteInbox", reflect.TypeOf((*MockInboxController)(nil).DeleteInbox), arg0)
}

// DeleteInboxRequests mocks base method.
func (m *MockInboxController) DeleteInboxRequests(arg0 *gin.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "DeleteInboxRequests", arg0)
}

// DeleteInboxRequests indicates an expected call of DeleteInboxRequests.
func (mr *MockInboxControllerMockRecorder) DeleteInboxRequests(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteInboxRequests", reflect.TypeOf((*MockInboxController)(nil).DeleteInboxRequests), arg0)
}

// GetInbox mocks base method.
func (m *MockInboxController) GetInbox(arg0 *gin.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "GetInbox", arg0)
}

// GetInbox indicates an expected call of GetInbox.
func (mr *MockInboxControllerMockRecorder) GetInbox(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetInbox", reflect.TypeOf((*MockInboxController)(nil).GetInbox), arg0)
}

// ListInbox mocks base method.
func (m *MockInboxController) ListInbox(arg0 *gin.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "ListInbox", arg0)
}

// ListInbox indicates an expected call of ListInbox.
func (mr *MockInboxControllerMockRecorder) ListInbox(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListInbox", reflect.TypeOf((*MockInboxController)(nil).ListInbox), arg0)
}

// RegisterInboxRequest mocks base method.
func (m *MockInboxController) RegisterInboxRequest(arg0 *gin.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "RegisterInboxRequest", arg0)
}

// RegisterInboxRequest indicates an expected call of RegisterInboxRequest.
func (mr *MockInboxControllerMockRecorder) RegisterInboxRequest(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RegisterInboxRequest", reflect.TypeOf((*MockInboxController)(nil).RegisterInboxRequest), arg0)
}

// RetryInboxRequestCallback mocks base method.
func (m *MockInboxController) RetryInboxRequestCallback(arg0 *gin.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "RetryInboxRequestCallback", arg0)
}

// RetryInboxRequestCallback indicates an expected call of RetryInboxRequestCallback.
func (mr *MockInboxControllerMockRecorder) RetryInboxRequestCallback(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RetryInboxRequestCallback", reflect.TypeOf((*MockInboxController)(nil).RetryInboxRequestCallback), arg0)
}

// UpdateInbox mocks base method.
func (m *MockInboxController) UpdateInbox(arg0 *gin.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "UpdateInbox", arg0)
}

// UpdateInbox indicates an expected call of UpdateInbox.
func (mr *MockInboxControllerMockRecorder) UpdateInbox(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateInbox", reflect.TypeOf((*MockInboxController)(nil).UpdateInbox), arg0)
}

// MockHealthHandler is a mock of HealthHandler interface.
type MockHealthHandler struct {
	ctrl     *gomock.Controller
	recorder *MockHealthHandlerMockRecorder
}

// MockHealthHandlerMockRecorder is the mock recorder for MockHealthHandler.
type MockHealthHandlerMockRecorder struct {
	mock *MockHealthHandler
}

// NewMockHealthHandler creates a new mock instance.
func NewMockHealthHandler(ctrl *gomock.Controller) *MockHealthHandler {
	mock := &MockHealthHandler{ctrl: ctrl}
	mock.recorder = &MockHealthHandlerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockHealthHandler) EXPECT() *MockHealthHandlerMockRecorder {
	return m.recorder
}

// Health mocks base method.
func (m *MockHealthHandler) Health(arg0 *gin.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Health", arg0)
}

// Health indicates an expected call of Health.
func (mr *MockHealthHandlerMockRecorder) Health(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Health", reflect.TypeOf((*MockHealthHandler)(nil).Health), arg0)
}

// MockUtilityHandler is a mock of UtilityHandler interface.
type MockUtilityHandler struct {
	ctrl     *gomock.Controller
	recorder *MockUtilityHandlerMockRecorder
}

// MockUtilityHandlerMockRecorder is the mock recorder for MockUtilityHandler.
type MockUtilityHandlerMockRecorder struct {
	mock *MockUtilityHandler
}

// NewMockUtilityHandler creates a new mock instance.
func NewMockUtilityHandler(ctrl *gomock.Controller) *MockUtilityHandler {
	mock := &MockUtilityHandler{ctrl: ctrl}
	mock.recorder = &MockUtilityHandlerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUtilityHandler) EXPECT() *MockUtilityHandlerMockRecorder {
	return m.recorder
}

// AcceptCookies mocks base method.
func (m *MockUtilityHandler) AcceptCookies(arg0 *gin.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "AcceptCookies", arg0)
}

// AcceptCookies indicates an expected call of AcceptCookies.
func (mr *MockUtilityHandlerMockRecorder) AcceptCookies(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AcceptCookies", reflect.TypeOf((*MockUtilityHandler)(nil).AcceptCookies), arg0)
}
