// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/jesusnoseq/request-inbox/pkg/login/provider (interfaces: ProviderManager)

// Package provider_mock is a generated GoMock package.
package provider_mock

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	provider "github.com/jesusnoseq/request-inbox/pkg/login/provider"
	model "github.com/jesusnoseq/request-inbox/pkg/model"
	oauth2 "golang.org/x/oauth2"
)

// MockProviderManager is a mock of ProviderManager interface.
type MockProviderManager struct {
	ctrl     *gomock.Controller
	recorder *MockProviderManagerMockRecorder
}

// MockProviderManagerMockRecorder is the mock recorder for MockProviderManager.
type MockProviderManagerMockRecorder struct {
	mock *MockProviderManager
}

// NewMockProviderManager creates a new mock instance.
func NewMockProviderManager(ctrl *gomock.Controller) *MockProviderManager {
	mock := &MockProviderManager{ctrl: ctrl}
	mock.recorder = &MockProviderManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProviderManager) EXPECT() *MockProviderManagerMockRecorder {
	return m.recorder
}

// ExtractUser mocks base method.
func (m *MockProviderManager) ExtractUser(arg0 string, arg1 *oauth2.Token, arg2 []byte) (model.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExtractUser", arg0, arg1, arg2)
	ret0, _ := ret[0].(model.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExtractUser indicates an expected call of ExtractUser.
func (mr *MockProviderManagerMockRecorder) ExtractUser(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExtractUser", reflect.TypeOf((*MockProviderManager)(nil).ExtractUser), arg0, arg1, arg2)
}

// GetOAuthConfig mocks base method.
func (m *MockProviderManager) GetOAuthConfig(arg0 string) (provider.OAuthConfig, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOAuthConfig", arg0)
	ret0, _ := ret[0].(provider.OAuthConfig)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// GetOAuthConfig indicates an expected call of GetOAuthConfig.
func (mr *MockProviderManagerMockRecorder) GetOAuthConfig(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOAuthConfig", reflect.TypeOf((*MockProviderManager)(nil).GetOAuthConfig), arg0)
}
