name: Deploy app

permissions:
  id-token: write
  contents: read

on:
  push:
    branches: ["main", "feat-move-deploy-code"]
    paths:
      - "front/**"
      - "api/**"
      - ".github/**"

env:
  TF_VAR_API_SNAPSHOT_VERSION: ${{ github.run_number }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger deploy workflow
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: jesusnoseq/request-inbox-deploy
          event-type: deploy
