name: Go CI

on:
  pull_request:
    branches: ["main"]
    paths:
      - "api/**"

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.21"
          cache-dependency-path: api/go.sum
      - name: Build
        run: go build -tags=jsoniter -v ./...
        working-directory: ./api
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          working-directory: api
      - name: Connect to AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-session-name: awssync_deploy_session
          role-to-assume: ${{secrets.AWS_IAM_ROLE}}
          aws-region: ${{secrets.AWS_REGION}}
      - name: Test
        run: go test -v ./...
        working-directory: ./api
