# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go CI

on:
  push:
    branches: ["main"]
    paths:
      - "api/**"
  pull_request:
    branches: ["main"]
    paths:
      - "api/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.21"
          cache-dependency-path: api/go.sum

      - name: Build
        run: go build -tags=jsoniter -v ./...
        working-directory: ./api

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          working-directory: api

      - name: Test
        run: go test -v ./...
        working-directory: ./api
