name: govulncheck

on:
  push:
    paths:
      - 'api/**'
  pull_request:
    paths:
      - 'api/**'
  schedule: # daily at 10:22 UTC
    - cron: '22 10 * * *'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  govulncheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          persist-credentials: false
      - uses: actions/setup-go@v6
        with:
          go-version-file: api/go.mod
      - run: |
          go run golang.org/x/vuln/cmd/govulncheck@latest ./...
        working-directory: ./api