name: React CI

on:
  pull_request:
    branches: [main]
    paths:
      - "front/**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20.x"
      - name: Install dependencies
        run: npm ci
        working-directory: ./front

      - name: Lint
        run: npm run lint
        working-directory: ./front

      - name: Build
        run: npm run build
        working-directory: ./front
